## General information
username: imauser
## Image and Image Tag
##
krak8s:
  image: quay.io/samsung_cnct/krak8s
  imageTag: latest
  imagePullPolicy: Always
  imagePullSecret:
  cloudProvider: none
  awsCredentials:
    # Each of the following values must be base64 encoded
    id:
    key:
    region:

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 768Mi

gitArchivist:
  image: quay.io/samsung_cnct/git-archivist
  imageTag: latest
  imagePullPolicy: Always
  imagePullSecret:

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi

## Should the service be LoadBalancer, NodePort or ClusterIP
## If you're using ingress, ClusterIP should be a solid choice
##
serviceType: ClusterIP

scheduling:
  affinity:
    node:
      type: requiredDuringSchedulingIgnoredDuringExecution
      labels:
#      - key: iamalabelkey
#        operator: In
#        values: ["value1", "value2"]
  tolerations:
#  - key: iamataintkey
#    value: taintvalue
#    effect: NoSchedule

networkPolicy:
  ingress:
#    enabled: true
#    namespaceLabels:
#      - key: tenant
#        value: customer1
#    podLabels:
#      - key: app
#        value: frontend
